name: Build test with Webpack
on:
  pull_request:
    branches:
      - develop
    paths:
      - 'frontend/**'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'ci-group'
  cancel-in-progress: false # 기존 작업 계속 수행
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to current repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock

      - name: Create .env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" > ./frontend/.env
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> ./frontend/.env
          echo "AMPLITUDE_KEY=${{ secrets.AMPLITUDE_KEY }}" >> ./frontend/.env
          echo "REACT_APP_GITHUB_CLIENT_ID"=${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}" >> ./frontend/.env
          echo "REACT_APP_REDIRECT_URI"=${{ secrets.REACT_APP_REDIRECT_URI }}" >> ./frontend/.env

      - name: Set environment file permissions
        run: chmod 644 ./frontend/.env

      # 프리플라이트 체크
      - name: Preflight Check for Environment Variables
        run: |
          if [ -z "${{ secrets.API_BASE_URL }}" ]; then
            echo "Error: API_BASE_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SENTRY_AUTH_TOKEN }}" ]; then
            echo "Error: SENTRY_AUTH_TOKEN is not set"
            exit 1
          fi
          if [ -z "${{ secrets.AMPLITUDE_KEY }}" ]; then
            echo "Error: AMPLITUDE_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}" ]; then
            echo "Error: REACT_APP_GITHUB_CLIENT_ID is not set"
            exit 1
          fi
          if [ -z "${{ secrets.REACT_APP_REDIRECT_URI }}" ]; then
            echo "Error: REACT_APP_REDIRECT_URI is not set"
            exit 1
          fi
        shell: bash

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: frontend

      - name: Run tests
        run: yarn test
        working-directory: frontend

      - name: Build
        run: yarn build
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
        working-directory: frontend
